nzzdev/Q-chart

helpers/data.js, routes/rendering-info/web.js
this makes the fixture `line - dates - min max - missing values` work as expected.
=> (min/max) fix min/max Y axis option if values are missing, fixes #61

chartTypes/dotplot/mapping.js, package-lock.json, package.json
fixes the issue with mixed up data if first dataseries value is lower than 2nd one.
=> Release 1.10.1

package-lock.json, package.json, resources/schema.json, routes/data.js, routes/download-data.js, routes/rendering-info/web.js, routes/routes.js, views/footer.html
=> download data in chart

Dockerfile, chartTypes/bar-stacked/mapping.js, chartTypes/bar/mapping.js, resources/fixtures/data/bar-stacked-dates-many-bars.json, routes/fixtures/data.js, test/e2e-tests.js
- makes the group padding dynamic depending on number of rows (as already done with the barWidth)
=> Feat bars group padding

chartTypes/bar/mapping.js, chartTypes/column/mapping.js, package-lock.json, package.json
- fix double labels with valuesOnBars and labelsOnTopOfBars for bar charts
=> Release 2.1.2

chartTypes/arrow/vega-spec.json, chartTypes/dotplot/vega-spec.json, config/d3.js, package-lock.json, package.json, resources/fixtures/data/dotplot-two-categories-same-value-min-max.json, routes/rendering-info/web-svg.js
- fix label overlap in arrow charts and dot plots X axis
- fix number format grouping
- fix /rendering-info/web joi validation rules
=> Release 3.0.1

chartTypes/area/mapping.js, chartTypes/arrow/mapping.js, chartTypes/bar-stacked/mapping.js, chartTypes/bar/mapping.js, chartTypes/column-stacked/mapping.js, chartTypes/column-stacked/vega-spec.json, chartTypes/column/mapping.js, chartTypes/commonMappings.js, chartTypes/dotplot/mapping.js, chartTypes/line/mapping.js
- labelBound for columns and dates: we can not show some dates if they would be outside the bounds of the axis with no harm
- if no axis title is given in the data, then we don't reserve space for it (act as if hideAxisLabel is set to true)
=> Fix small visual bugs

README.md, chartTypes/commonMappings.js, chartTypes/line/mapping.js, package-lock.json, package.json
- Update maintainer
- (bar/line/area) Fix prognosisStartDate comparison expressions
=> Release 3.1.5

package-lock.json, package.json, resources/locales/de/translation.json, resources/locales/en/translation.json, resources/locales/fr/translation.json, resources/schema.json, routes/notification/supportedDateFormat.js, routes/routes.js
- Adds notification for valid date format
=> Release v3.3.0

styles_src/q-chart.scss, views/events.html
chart item on staging follows as soon as I have the necessary rights on the ranger to upload the my branch
=> fix annotation indent

chartTypes/bar-stacked/mapping.js, resources/fixtures/data/bar-stacked-mixed-values-on-bars.json, routes/fixtures/data.js, routes/option-availability.js
Adresses the following todo:
https://3.basecamp.com/3500782/buckets/1333707/todos/2453011428
Editor example: 
https://q.st-test.nzz.ch/editor/chart/e9046b127bd99afc9cd208b94d18b478
New fixture: 
bar-stacked-mixed-values-on-bars.json
=> Feature stacked bar values on bars

chartTypes/area/vega-spec.json, chartTypes/line/vega-spec.json, package-lock.json, package.json
- (area, line) show start and end label on mobile if numberOfLabels option is set to many
=> Release 3.5.2

package-lock.json, package.json, views/events.html
- Refactor to legend annotation from sophie-q
=> Release v3.6.0

chartTypes/bar-stacked/mapping.js, chartTypes/bar-stacked/vega-spec.json, chartTypes/bar/mapping.js, chartTypes/bar/vega-spec.json, chartTypes/commonPostprocessings.js, helpers/elementModify.js
https://3.basecamp.com/3500782/buckets/1333707/todos/2480040725
Example:
- https://q.st-staging.nzz.ch/item/e9046b127bd99afc9cd208b94d1b2310
- https://q.st-staging.nzz.ch/item/e9046b127bd99afc9cd208b94d1b17cd
- https://q.st-staging.nzz.ch/item/e9046b127bd99afc9cd208b94d1a5183
=> Fix bar chart center label

chartTypes/bar-stacked/mapping.js, chartTypes/bar/mapping.js
Test here: https://q.st-staging.nzz.ch/item/e9046b127bd99afc9cd208b94d294f74
Production and Graphics are both fine with the outcome of this change.
=> change bar height

helpers/dateSeries.js, package.json
Fix date annotations without leading zero
=> Release 3.6.4

chartTypes/column/postprocessings.js, chartTypes/commonMappings.js, chartTypes/commonPostprocessings.js, resources/fixtures/data/bar-axislabel-overlap.json, routes/fixtures/data.js
Fix axislabel in column charts with dates
=> Release 3.6.5

package-lock.json, package.json
- Revert update vega see https://github.com/nzzdev/Q-chart/issues/190 for more details
=> Release 3.6.7

resources/locales/de/translation.json, resources/locales/en/translation.json, resources/locales/fr/translation.json, resources/schema.json, routes/notification/tooManyData.js, routes/notification/tooManyRows.js, routes/routes.js
- New notification, when 600 or more data points were entered.
Test here: https://q.st-test.nzz.ch/item/e9046b127bd99afc9cd208b94d5674dd
=> add notification

README.md, chartTypes/bar-stacked/mapping.js, chartTypes/bar/mapping.js, package-lock.json, package.json
- Add padding for text label on bar chart 
- https://3.basecamp.com/3500782/buckets/1333707/todos/4351571149
- https://q.st-staging.nzz.ch/item/e9046b127bd99afc9cd208b94d6c6ee8
- https://q.st-staging.nzz.ch/item/e9046b127bd99afc9cd208b94d6c0763
=> Release 3.7.4

routes/rendering-info/web.js
Deployed on Stage
Test here:
https://q.st-staging.nzz.ch/item/71b560c075f23d2f41e0089664961725
https://q.st-staging.nzz.ch/item/ecf1db20c4ca6dcf6e790990670989f7
https://q.st-staging.nzz.ch/item/71b560c075f23d2f41e0089664961117
https://q.st-staging.nzz.ch/item/71b560c075f23d2f41e0089664960b1b
https://q.st-staging.nzz.ch/item/71b560c075f23d2f41e00896649603df
=> restrict removing highlightDataSeries to line charts

chartTypes/area/postprocessings.js, chartTypes/bar/mapping.js, chartTypes/commonPostprocessings.js, chartTypes/line/postprocessings.js
Applies monoblock only if all labels are numbers
=> Add monoblock y axis labels for line & area chart

chartTypes/area/postprocessings.js, chartTypes/bar/mapping.js, chartTypes/commonPostprocessings.js, chartTypes/line/postprocessings.js, package-lock.json, package.json
- Add monoblock y axis labels for line & area chart
- Fix title assertion in case that there is no title
=> Release 3.9.8
