nzzdev/Q-chart

- chartTypes/bar-stacked/mapping.js
- chartTypes/column-stacked/mapping.js
- resources/fixtures/data/bar-stacked-100.json
- routes/fixtures/data.js
In case stacked bars sum up to 100 it's most often a percentage that is shown. In this case we want to have a tick at 50%, especially when it's about vote results.
This PR sets fixed tick values in case all sums are 100 for stacked bars and columns.
> (stacked bar/column) set ticks to 0/25/50/75/100 if all sums are 100

- .vscode/launch.json
- chartTypes/arrow/mapping.js
- chartTypes/bar-stacked/mapping.js
- chartTypes/bar/mapping.js
- chartTypes/column-stacked/mapping.js
- chartTypes/column/mapping.js
- chartTypes/commonMappings.js
- chartTypes/dotplot/mapping.js
- chartTypes/line/mapping.js
- helpers/data.js
- helpers/itemVegaMapping.js
- resources/display-options-schema.json
- routes/option-availability.js
- routes/rendering-info/web-svg.js
- routes/rendering-info/web.js
- This PR implements the height calculation based on displayOption `size`
- This branch is deployed on staging, so it can be tested in Staging LivingDocs -> https://edit-stage.nzz.ch/articles/15611/edit/add
- The `size` option is only available for charttypes `line`, `column` and `stacked-column`
- In a regular article (width of 560px) charts with `size` `basic` have a height of `240px` and with axis label `260px`
- With `size` `prominent` they have a height of `315px` and with axis label `335px`
- Closes https://github.com/nzzdev/Q-chart/issues/99
> Feat aspect ratio

- package-lock.json
- package.json
- routes/rendering-info/web-svg.js
- This is a bugfix release
- Fixes a problem with bar charts with single columns. The label was not shown above the bar because the width was not passed to `mappingData`
> Release 1.13.2

- chartTypes/bar-stacked/mapping.js
- resources/fixtures/data/bar-stacked-100.json
- implements #98 
- deployed on test
- can be tested using fixture item `chart-10` on test env
- other bar charts should still show the labels on the Y axis
> Feat hide label if one bar

- resources/display-options-schema.json
- resources/schema.json
- routes/dynamic-enum.js
- routes/notification/hideAxisLabel.js
- routes/notification/shouldBeBarChart.js
- routes/notification/shouldBeBars.js
- routes/notification/shouldBeLineChart.js
- routes/notification/unsupportedDateFormat.js
- routes/option-availability.js
- This PR adjusts the schema of availability-checks, notification-checks and dynamic-enums
- All the properties specific to a check live now in the config object. The properties specific to the type of check (`priority`) live next to the type property:
```json
{
"type": "ToolEndpoint",
"config": {
"endpoint": "notification/unsupportedDateFormat",
"fields": ["data"],
"options": {
"limit": 8
}
},
"priority": {
"type": "medium",
"value": 3
}
}
```
- All the checks now make use of the `fields` property to define which parts of the item are needed for the check
- The ToolEndpoint receives now an object containing the `item` and an optional `options` object (the corresponding routes (notifications, option-availability and dynamic-enums) where updated to reflect this change) 
- This branch will …
> Adjust the schema of availability-checks, notification-checks and dynamic-enums

- package-lock.json
- package.json
- routes/dynamic-schema.js
- Fixes a bug where the enum for `colorOverwritesRows` included the header row as well
- The logic for the overwrite index number can stay the same (as to achieve the correct overwrite, one had to select the wrong line)
> Release 2.0.2

- chartTypes/dotplot/mapping.js
- cli-config.js
- resources/fixtures/data/dotplot-floating-point.json
- uses `config.axis.labelColorLight` for not-highlighted connect-dot-lines and annotations if given, falls back to `config.axis.labelColor` for backwards compatibility
> (dots) fix highlighting rows 

- chartTypes/area/mapping.js
- chartTypes/arrow/mapping.js
- chartTypes/bar-stacked/mapping.js
- chartTypes/bar/mapping.js
- chartTypes/column-stacked/mapping.js
- chartTypes/column-stacked/vega-spec.json
- chartTypes/column/mapping.js
- chartTypes/commonMappings.js
- chartTypes/dotplot/mapping.js
- chartTypes/line/mapping.js
- package-lock.json
- package.json
- fix: line charts with missing values (null) and prognosis render correctly
- fix: if no axis title is given (empty cell) no space is reserved for the title
- some other small fixes
> Release 3.1.1

- chartTypes/commonMappings.js
- chartTypes/line/mapping.js
Use timestamps directly instead of using timeFormat with `%Q`.
`timeFormat` returns a string, which would lead to wrong comparisons for timestamps before/after 9 September 2001 (Unix time 1000000000, dates before have Unix time starting with 9, which makes them "greater" for string comparison, e.g. "999" > "1000" is true)
See https://3.basecamp.com/3500782/buckets/1333707/todos/2164074609
Before:
After:
> (bar/line/area) Fix prognosisStartDate comparison expressions

- chartTypes/column-stacked/vega-spec.json
- chartTypes/column/vega-spec.json
This gives some more space to the first and last label.
Fixes [this issue](https://3.basecamp.com/3500782/buckets/1333707/todos/2233603449).
> Add some paddingOuter to column charts

- package-lock.json
- package.json
- resources/schema.json
- routes/notification/unsupportedDateFormatEvents.js
- Set an empty string default value for all required field of event-point and event-range.
- Do not show unsupported date format warning if date field is empty.
The first change fixes [a bug](https://3.basecamp.com/3500782/buckets/1333707/todos/2411966118) where it was not possible to add event / time span annotations for existing charts.
If required fields do not have a default value, they are "undefined", and so a newly created event does not validate against the event-point or event-range schema.
Relevant code in Q-Editor:
https://github.com/nzzdev/Q-editor/blob/9ed126b2a9ca1fee214130c902c957f02f1ec79f/client/src/elements/schema-editor/schema-editor-array.js#L264-L273
Deployed on staging, test example here:
https://q.st-staging.nzz.ch/item/6dcf203a5c5f74b61aeea0cb0ee5d4e6
> Fix adding events to existing charts

- Dockerfile
- chartTypes/commonPostprocessings.js
- package-lock.json
- package.json
Fix bug in `highlightZeroGridLineIfPositiveAndNegative` postprocessing by removing highlighting of tick lines which do not exist anymore.
The following was happening before:
- For charts with positive and negative values, the code to highlight the zero line was called
- An exception was thrown for the access to the result of querySelector(".role-axis-tick") that
returned null (because there are no y axis ticks).
- The exception was caught, but all postprocessings afterwards were not carried out
- for line charts: highlight zero line, outlines for annotation labels, reverse line order
- for area charts: highlight zero line
=> these are now working again
Bug introduced in 5ee98b6 when the y axis ticks were removed.
See also
- [Discussion about outlines for annotation labels on …
> Release 3.2.2

- chartTypes/arrow/mapping.js
- chartTypes/bar-stacked/mapping.js
- chartTypes/dotplot/mapping.js
- resources/fixtures/data/bar-stacked-null-values.json
- routes/fixtures/data.js
- test/e2e-tests.js
This PR fixes a bug where stacked-bar charts where broken, if they included empty values:
Before: https://q.st-staging.nzz.ch/item/e9046b127bd99afc9cd208b94d03b242
After: https://q.st-test.nzz.ch/item/chart-25
This bug was introduced because we started using decimal.js to check if the values sum up to 100: https://github.com/nzzdev/Q-chart/commit/c6c6218a4e6d17609c82c3ce25cd719a45d6c9a6. Decimal.js throws an exception if non-numeric are passed.
[Code change without formating](https://github.com/nzzdev/Q-chart/commit/32e2edae8e91c3e71a0f73351913b37d6cf4c661)
Stories containing affected charts:
- https://www.nzz.ch/zuerich/zuerich-waehlt-die-resultate-im-ueberblick-ld.1359973
- https://www.nzz.ch/international/wie-die-grosse-koalition-immer-kleiner-wurde-ld.1486791
> Handle null values in StackedBar charts

- chartTypes/line/mapping.js
- helpers/events.js
- resources/fixtures/data/line-stock-chart.json
Problem: Intraday charts do not have a linear time axis, because the stock market is closed during the night.
Instead, there is a "jump" during the night, such that e.g. Thursday 16:50 => 17:00 is the same step on the x axis as Thursday 17:00 => Friday 8:00.
This situation was not properly handled for event annotations before and is fixed here.
Event annotations are also added to the stock chart fixture for testing.
See https://3.basecamp.com/3500782/buckets/1333707/todos/3077999117
Deployed on staging with relevant example here: https://q.st-staging.nzz.ch/item/e9046b127bd99afc9cd208b94d06c6f4
> Release 3.2.5

- resources/locales/de/translation.json
- resources/locales/en/translation.json
- resources/locales/fr/translation.json
- resources/schema.json
- routes/notification/supportedDateFormat.js
- routes/routes.js
Our editors regularly enter data with an unsupported date format. Often they struggle to detect the problem by themselves, because Q doesn't provide any indication of a problem. There is already a notification which is shown when an unsupported date format is detected. But often Q can't detect an unsupported date format, because it's hard to create a logic which can differentiate between an unsupported date format and regular text.
We are introducing a new notification which is always shown when a date format was detected. We will communicated this change to our editors and remind them of the documentation on supported date formats. If an editor enters date with a dateseries and the notification is not shown, they know that the date format is not supported.
This PR is deployed on test: …
> Add notification for valid date format

- index.js
- package-lock.json
- package.json
Remove modification of the FONTCONFIG_PATH / PANGOCAIRO_BACKEND environment variables.
Starting with node-canvas v2, the modification of these settings is no longer required
according to https://medium.com/@adamhooper/fonts-in-node-canvas-bbf0b6b0cabf
We observed that fonts were not loaded from resources/fonts with these modified
environment variables on macOS.
With this change, fonts are loaded correctly on macOS and Ubuntu 18.
How to test
- Make sure that the nzz-sans-serif font is not installed in the system.
- Run the chart tool with the following entry in the FONTS array and verify
that the measure width test displays 54
> Release 3.3.1

- README.md
- chartTypes/area/mapping.js
- chartTypes/arrow/mapping.js
- chartTypes/bar-stacked/mapping.js
- chartTypes/bar/mapping.js
- chartTypes/column-stacked/mapping.js
- chartTypes/column/mapping.js
- chartTypes/commonPrerender.js
- chartTypes/dotplot/mapping.js
- chartTypes/line/mapping.js
- helpers/data.js
- resources/fixtures/data/bar-large-numbers-auto.json
- resources/fixtures/data/bar-large-numbers-divide-by-1.json
- resources/locales/en/translation.json
- resources/locales/fr/translation.json
- resources/schema.json
- routes/fixtures/data.js
- routes/rendering-info/web.js
- Add `largeNumbers` => `divideBy` option, including fixture data, documentation, and translations
- Adapt logic for automatic divisor: Keep full numbers up to 99 999, divide if >= 100k
> Feat large numbers

- .vscode/launch.json
- chartTypes/area/vega-spec.json
- resources/fixtures/data/area-y-legend-thousand-separator.json
- routes/fixtures/data.js
- test/config/toolRuntimeConfig.json
- test/dom-tests.js
Flag format in the vega configuration of the area was deleted. For the other charts, this was done in the following PR:
* #143
* #156
* [Chart - Flächendiagramm kein viertelgeviert](https://3.basecamp.com/3500782/buckets/1333707/todos/3390763757)
* https://q.st-test.nzz.ch/item/chart-2
> Fix area chart number format

- styles_src/q-chart.scss
- views/events.html
On mobile phones with small screen sizes, the label overlaps the icon.
Before fix:
After fix
Example
* https://q.st-test.nzz.ch/item/chart-45
* https://www-test.nzz.ch/test/first-test-ld.1340834
> Fix annotation overflow label

- Dockerfile
- chartTypes/area/vega-spec.json
- chartTypes/line/vega-spec.json
- config/vega-default.json
- helpers/textMeasure.js
This PR fixes a bug in the text measure logic. The chart tool uses the [node-canvas module](https://github.com/Automattic/node-canvas) to measure the width of a text label on server-side. This width is used to determine if a label should be hidden or how much space should be made available for the label. 
The bug was that font string that is passed to the canvas context looked like this before `context.font = "100 11 nzz-sans-serif"`. The font string has to follow the same logic as a regular [css font string](https://developer.mozilla.org/en-US/docs/Web/CSS/font). So it was missing the `px` for the font-size value. This PR fixes that to `context.font = "100 11px nzz-sans-serif"`. The canvas module couldn't parse this string before and used the default font string which is `10 sans-serif`. …
> Fix cut off axis labels

- chartTypes/area/vega-spec.json
- chartTypes/line/vega-spec.json
This PR improves visible labels on mobile if labels option is set to many for area and line charts. The `labelFlush` property is set to 24px. This value was determined through testing. The [labelFlush property ](https://vega.github.io/vega/docs/axes/) indicates if labels at the beginning or end of the axis should be aligned flush with the scale range. The number indicates a pixel distance threshold: labels with anchor coordinates within the threshold distance for an axis end-point will be flush-adjusted.
[Before:](https://q.st.nzz.ch/item/26356a1918b687a3e1a7ff0d5edeec77)
[After:](https://q.st-test.nzz.ch/item/e9046b127bd99afc9cd208b94d19f37b)
This PR is deployed [on test](https://q.st-test.nzz.ch/item/e9046b127bd99afc9cd208b94d19f37b)
> Show start and end label on mobile if labels option is set to many

- chartTypes/dotplot/mapping.js
- resources/fixtures/data/dotplot-years-threshold.json
- resources/schema.json
- routes/fixtures/data.js
Addresses the following issue: 
https://3.basecamp.com/3500782/buckets/1333707/todos/2372408275
Includes fixture tailored to the fix dotplot-years-threshold.json
Two main steps happened:
First estimating the pixel value, for which I try to evaluate the width/data unit ratio and come up with an estimation. Would be definitely nicer if there would be a better way in Vega. It still works in most cases.
Second I remove the occurrence check from the item loop and introduce the threshold check on the already sorted array. This way I could work with the difference between points and the estimated unit pixel to decide if they overlap enough or not.
> Fix dotplot overlap threshold

- views/header.html
The original issue was, that there was an unexplainable whitespace on top of the subtitle, when the chart was rendered as print version. Problem was a "nunjucks peculiarity" regarding whitespace-control (https://mozilla.github.io/nunjucks/templating.html#whitespace-control).
Test here: https://q.st-staging.nzz.ch/item/chart-52
> remove whitespace on top of subtitle

- helpers/dateSeries.js
Addresses the following issue: 
https://3.basecamp.com/3500782/buckets/1333707/todos/3860502252
Despite the complicated nature of dates, the function for formatting with d3 made this an easy fix.
The changes in nutshell: the dash ( %d --> %-d ) means no spacing, overriding the default zero leading. The unicode character is the thin space (viertelgeviert).  
The change requested to be everywhere, where numeric day and month appears.
Tested on most charts with different dates (fixtures and charts on staging).
> Fix date format no leading zero

- chartTypes/column/postprocessings.js
- chartTypes/commonMappings.js
- chartTypes/commonPostprocessings.js
- resources/fixtures/data/bar-axislabel-overlap.json
- routes/fixtures/data.js
Addresses the following issue: 
https://3.basecamp.com/3500782/buckets/1333707/todos/3860502110
The good in this solution is that it is only uses Vega expression and should only target date series in column charts (which is the issue about).
I figured out that the combination of no bound, zero flush and greedy overlap will solve the issue, although the first and last labels are reaching out of bound of axis, yet they still remain visible in the chart frame. 
The ideal solution could be aligning them to the respective axis edges,  but after trying out some methods I arrived to the conclusion that a more precise solution would take a disproportionate amount of time and energy. 
Testen on some charts on staging.
Fixture of the original issue chart included.
> fix axislabel overlap test

- chartTypes/line/mapping.js
adresses the following issue with 3.6.8. :
https://3.basecamp.com/3500782/buckets/1333707/todos/4028134101
The problem was appearing in charts with prognosis lines. The prognosis is made by cloning the existing Vega mark and create two, one till the prognosis date and one from. The cloning happened on the zero array element of marks, which after 3.6.8. was the background highlight of the line. So those were insvisible if there was no highlight set, or white if it was set. The change copies both the highlight and the actual line.
> fix prognosis highlight

- chartTypes/line/mapping.js
- chartTypes/line/vega-spec.json
This PR resolves this issue: https://3.basecamp.com/3500782/buckets/1333707/todos/4124664332
In https://github.com/nzzdev/Q-chart/pull/231 the visibility of highlighted lines where improved by adding a white border. This is achieved by drawing two lines on top of each other. One a bit thinker with white color and another a bit thinner with the line color. 
In that PR it was forgotten to adjust the lineInterpolation option to update both lines with the given interpolation. This PR fixes this issue.
This PR can be tested by checking [this graphic](https://q.st-test.nzz.ch/item/e9046b127bd99afc9cd208b94d596160) on test environment. [The same graphic](https://q.st-staging.nzz.ch/item/e9046b127bd99afc9cd208b94d592f25) is also on staging environment, where the lineInterpolation is not working.
> (line) Set interpolate property on both marks

- chartTypes/line/mapping.js
- chartTypes/line/vega-spec.json
- package-lock.json
- package.json
- (line) Fixes `interpolateLine` property (see https://github.com/nzzdev/Q-chart/pull/237)
> Release v3.6.11

- chartTypes/area/vega-spec.json
- chartTypes/line/vega-spec.json
- test/dom-tests.js
This PR adjusts the y-axis tick values of area and line charts. The nice value ([see vega documentation](https://vega.github.io/vega/docs/scales/)) was adjust from 4 to true. This makes vega calculate round y-axis tick values based on the domain. Before this change it was defined that 4 y-axis tick values should be calculated within the domain. For some charts this resulted in unexpected behaviour.
Before this change:
Vega was calculating 4 y-axis tick values and added one negative tick because there is a single negative value in the dataset.
After this change:
Vega calculates the y-axis tick values by itself and doesn't show a negative y-axis tick for the single negative value in the dataset.
This branch is deployed on Test-Environment: …
> (area, line) Adjust nice value to improve y-axis tick values

- chartTypes/bar-stacked/mapping.js
This PR changes the alignment of valuesOnBars on stacked bar charts to the end of the bar.
Before:
After:
This branch is deployed on test environment: https://q.st-test.nzz.ch/item/e9046b127bd99afc9cd208b94d5aa445
See also [this Basecamp-ToDo](https://3.basecamp.com/3500782/buckets/1333707/todos/4199212117) where the discussion on the position of the values is documented. We are intending to try this out and if we find problems with it plan a project where we try to find a better solution for it.
> (bar-stacked) Align valuesOnBars to the end of the bar

- chartTypes/column-stacked/postprocessings.js
This PR adds `showOnlyFirstAndLastLabel` postprocessing step to `column-stacked` chart type. This was already added to `column` chart type in https://github.com/nzzdev/Q-chart/pull/225, but was forgotten to also add to `column-stacked`.
Before:
After:
> (column-stacked) Add showOnlyFirstAndLastLabel postprocessing

- .vscode/launch.json
- routes/rendering-info/web.js
- add new property in toolRuntimeConfig for removing line highlight. This is mainly a print issue, because highlighting certain lines makes the rest appear very light and some people can't see them properly anymore.
- pull request for Q-server-nzz: https://github.com/nzzdev/Q-server-nzz/pull/507
- Test here: https://q.st-staging.nzz.ch/item/ecf1db20c4ca6dcf6e790990670989f7
> remove line highlight in print
